import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Raigato Next Typescript Template 🐊</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Raigato Next Typescript Template 🐊</h1>
      </main>
    </>
  )
}
